#!/usr/bin/python
# -*- coding: utf_8 -*-
import urllib
import urllib2
from crawl_working_1 import get_start_link, Link, get_end_link 

url_utf8 = "http://en.wikipedia.org/wiki/Paul_Erdős"
url_encoded = "http://en.wikipedia.org/wiki/Paul_Erd%C5%91s"
result = urllib2.urlopen(url_utf8)
source = result.read()

end_link = 0
start_link = get_start_link(source, end_link) 
end_link = get_end_link(source, start_link)
title = Link.extract_link_title(source, end_link)

f = open("title","w")
f.write(title+"\n\n\n")
f.close()